### ISSUE TITLE
MoarVM panic: Internal error

### ISSUE THREAD

**Issue by demanuel** [MoarVM/MoarVM#1849]
Sometimes when running my code it dies with one of the following errors:

- MoarVM panic: Internal error: invalid thread ID -1205635208 in GC work pass
- MoarVM panic: Internal error: zeroed target thread ID in work pass

This happens once in every 50 runs.

**Comment by timo** [comment]
This is a sign of memory corruption, which can happen in many different ways, but often it comes from using something that is not thread safe from multiple threads simultaneously.

It's not very likely to give a lot of additional information, but you could try running your code with `rakudo-valgrind-m` or just `valgrind rakudo bla bla` to have it check for definitely-bogus memory accesses.

if you're up for it, using mozilla's rr to `rr record -h rakudo blabla` lets you make a recording that you can reliably replay and debug forwards and backwards as often as you like once you get the 1/50 crash to happen inside it, and you can `rr pack` and send it to someone else to investigate if you don't want to do it yourself.

Otherwise, without access to your source code, this issue is not actionable, but I am going to open a new issue to collect ideas for how to make the error messages better.

**Comment by demanuel** [comment]
@timo Hi Timo! This is a very nice info. Let me see what i can do with it.

**Comment by demanuel** [comment]
@timo unfortunately rr throws an exception and valgrind makes it painfully slow to run. I don't think i can provide more info :-(
