### ISSUE TITLE
Build failure on Mac OS X: file was built for archive which is not the architecture being linked (x86_64)

### ISSUE THREAD

**Issue by briandfoy** [MoarVM/MoarVM#334]
I'm trying to build Moar from the latest on GitHub and the download on MoarVM.org. I keep getting an error about third-party libraries:

ld: warning: ld: warning: ld: warning: ignoring file 3rdparty/libatomic_ops/src/libatomic_ops.a, file was built for archive which is not the architecture being linked (x86_64): 3rdparty/libatomic_ops/src/libatomic_ops.aignoring file 3rdparty/tinymt/libtinymt.a, file was built for archive which is not the architecture being linked (x86_64): 3rdparty/tinymt/libtinymt.aignoring file 3rdparty/sha1/libsha1.a, file was built for archive which is not the architecture being linked (x86_64): 3rdparty/sha1/libsha1.a

Let me know what you'd like to know about my system; it's a basic Mac OS X setup.

**Comment by FROGGS** [comment]
Hi, can we get the entire build output, starting with the output of Configure.pl?

**Comment by coke** [comment]
Also output of ```sw_vers``` and any options passed to Configure.pl (just did a build here on 10.10.5 with no issues)

**Comment by raiph** [comment]
geekosaur's comments from http://irclog.perlgeek.de/moarvm/2016-01-16#i_11896132

you might run lipo -detailed_info against the archive

to see what it says

but: there si a case macports has seen where someone had the wrong dev tools on their system and ended up with archives that had the correct objects in them but no symbol table. ld erroneously reports this as "which is not the architecture being linked"

if lipo confirms that the archive has the right arch objects in it, see if "otool -S" produces output.

if it doesn't, then look for extra (incorrect) versions of ar, ranlib, and/or ld. (also check that Configure.pl is finding the ones it should be) (the specific case we saw was someone had installed the iOS dev kit incorrectly and some things were finding the ARM cross-dev versions of ar and ranlib)

...actually just ranlib was the wrong one

but you can also see this if building 64-bit objects and then somehow have a 32-bit-only ranlib or ar sitting around; ar will build valid archives without a symbol table, ranlib won't add a symbol table

...ld will report the wrong thing

and that 32-bit thing can happen pretty easily if this is a system upgraded from Tiger or Leopard because xcode 4 and later do not remove earlier 32-bit xcode that lived under /Developer

and random stuff will use the old /Developer 32-bit versions :/

(or Snow Leopard for that matter, although its /Developer is more likely to at least be 64 bit capable)

**Comment by briandfoy** [comment]
Here's the output from Configure.pl (no args) and make. I'm using whatever Apple supplies in the developer tools.

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27

[make.txt](https://github.com/MoarVM/MoarVM/files/102671/make.txt)
[configure.txt](https://github.com/MoarVM/MoarVM/files/102672/configure.txt)

**Comment by briandfoy** [comment]
I think Sinan and I have figured this out (mostly Sinan though).

When I run configure, it recognizes darwin and selects clang as the compiler. AR is set to merely ar, but that first finds the gnu version in my path instead of the one that goes with clang. When we change the search path around to the first ar is Apple's, everything works.

However, trying `Configure.pl --toolchain gnu` still chose clang instead of gcc. I don't particularly care which one it uses (at least right now) as long as the other tools come from the right set. I know that I can individually set the paths with args to Configure.pl, but I wouldn't expect to have to do that. I bet most people don't even know what ar is or why they'd set one over the other.

I don't have any advice on this. My problem has a solution, but the Configure could be smarter about this. You can close this issue (maybe opening a fresh one for more smartness).

**Comment by bdw** [comment]
Thanks for looking into this. I'll close this ticket for now, but it's certain we'll need more smartness in Configure.pl
