### ISSUE TITLE
"double free or corruption" in MVM_gc_collect_free_nursery_uncopied on 2016.08

### ISSUE THREAD

**Issue by avuserow** [MoarVM/MoarVM#398]
My Perl 6 setup is the result of `rakudobrew build moar` yesterday, so it's some arbitrary revision, not a release version, but hopefully this report is helpful nonetheless. My rakudobrew checkout is at revision `6a8278cd5d92e87c7c3ade70fbb0a3019e961bae`.

perl6 -v: `This is Rakudo version 2016.08.1-46-g6a8278c built on MoarVM version 2016.08
implementing Perl 6.c.`

moar --version: `This is MoarVM version 2016.08 built with JIT support`

gcc --version: `gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)`
uname -a: `Linux beaujolais 4.4.14-200.fc22.x86_64 #1 SMP Fri Jun 24 21:19:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
free -m: `Mem:           7844         912        4296          16        2635        6602` (with no swap)

The code itself is attached. Some of the interesting things appear to be object construction, `trait_mod:<is>`, an object hash, and the incorrect use of a `PROXY`. I've attempted to golf down my code a bit, but didn't get too far given that the stacktrace mentions GC. The `test2.p6` script can be run with any argument (it's unused but the argument itself seems needed to crash). I have the `BinaryScanner.pm6` file in a `lib` subdirectory relative to my main program.

This crash happens fairly often (maybe 80-90% of the time), but seems to never happen on the first run of the code after being modified. The stacktrace is attached.

[moar-stacktrace.txt](https://github.com/MoarVM/MoarVM/files/441323/moar-stacktrace.txt)

I golfed this down on the revision above, here are the modified files:
[test2.p6.txt](https://github.com/MoarVM/MoarVM/files/441324/test2.p6.txt)
[BinaryScanner.pm6.txt](https://github.com/MoarVM/MoarVM/files/441326/BinaryScanner.pm6.txt)

I also rebuilt the most current `moar-nom` (2016.08.1-47-gd43ea07) using rakudobrew (as of a few minutes ago) and tried it out. It didn't crash with the above golfed files, but did crash with the ungolfed versions, which I've attached below.

[ungolfed test2.p6.txt](https://github.com/MoarVM/MoarVM/files/441336/test2.p6.txt)
[ungolfed BinaryScanner.pm6.txt](https://github.com/MoarVM/MoarVM/files/441335/BinaryScanner.pm6.txt)

**Comment by timo** [comment]
i don't know how, but we get a hint passed in a getattr operation that's out of bounds for the given type, so we end up taking a pointer to memory outside that particular array in the reprdata and then ... i guess all hell breaks loose?

i could put a bounds check in, but it'd be very important to figure out how in the hell we're getting a wrong hint generated in the first place.

It could very well be that it's caused by you building methods for the proxy and the hint is generated for the enclosing class, then re-used for the proxy and at that point it explodes. If we just put in a bounds check, we could very well end up with hints that are in-bounds and point at any random field in that final class ...

**Comment by timo** [comment]
I committed the bounds check. The issue now becomes one of code-gen, because with the bounds check it doesn't crash, it'll just throw an exception, and that's fine from moarvm's side. We ought to track this bug in nqp or maybe the perl6 bug queue on RT from now on.
