### ISSUE TITLE
Uninitialized variable 'body' was used. The variable was used to initialize itself.

### ISSUE THREAD

**Issue by FROGGS** [MoarVM/MoarVM#430]
https://github.com/MoarVM/MoarVM/blob/master/src/jit/emit_x64.dasc#L542

```
Viva64-EM
full
542
/nfs/home/dmka/src/rakudo-star-2016.07/MoarVM/src/jit/emit_x64.dasc
error
V573
Uninitialized variable 'body' was used. The variable was used to initialize itself.
false
1
        MVMint16 offset = ins->operands[2].lit_i16;
        MVMint16 body   = offsetof(MVMP6opaque, body);
        /* load address and object */
```

Found by Dmitry Karasik.

**Comment by jnthn** [comment]
Wonder if this is a false positive from static analysis? `offsetof` is a [macro that treats the second argument as a field name](https://en.wikipedia.org/wiki/Offsetof), so it's actually talking about the body field of `P6opaque`. Since macros are expanded prior to any compilation taking place, this will be rewritten into a struct indexing (or a special compiler form) before there's any chance for confusion with the body variable.
