### ISSUE TITLE
Cannot decode UTF-8 in this file's name

### ISSUE THREAD

**Issue by samcv** [MoarVM/MoarVM#525]
https://archive.org/download/musopen-dvd/Musopen-DVD.zip/Musopen%20DVD%2FBrahms%20-%20Symphony%20No%201%20in%20C%20Major%2FSymphony%20No.%201%20in%20C%20Minor%2C%20Op.%2068%20-%20IV.%20Adagio%20-%20Piu%CC%80%20andante%20-%20Allegro%20non%20troppo%2C%20ma%20con%20brio.mp3

Other programs like perl for example are able to decode it fine, but 
Running `perl6 -e dir.say`
```
("Symphony No. 1 in C Minor, Op. 68 - IV. Adagio - Piu􏿽xCC􏿽x80 andante - Allegro non troppo, ma con brio.mp3".IO "perl.pl".IO)
```
Running `perl6 -e dir.ords.perl.say
```
(83, 121, 109, 112, 104, 111, 110, 121, 32, 78, 111, 46, 32, 49, 32, 105, 110, 32, 67, 32, 77, 105, 110, 111, 114, 44, 32, 79, 112, 46, 32, 54, 56, 32, 45, 32, 73, 86, 46, 32, 65, 100, 97, 103, 105, 111, 32, 45, 32, 80, 105, 117, 1114109, 120, 67, 67, 1114109, 120, 56, 48, 32, 97, 110, 100, 97, 110, 116, 101, 32, 45, 32, 65, 108, 108, 101, 103, 114, 111, 32, 110, 111, 110, 32, 116, 114, 111, 112, 112, 111, 44, 32, 109, 97, 32, 99, 111, 110, 32, 98, 114, 105, 111, 46, 109, 112, 51, 32, 112, 101, 114, 108, 46, 112, 108).Seq
```
Notice the 1114109 which is <Plane 16 Private Use>

**Comment by dmhursh** [comment]
I'm not sure if this helps or not, but the data I was dealing with didn't enter perl6 directly from the filesystem.

  - The file is on disk with the (perhaps bad) name using a 3 byte 'ù'.
  - Banshee, a music player (written in mono I believe) scanned the disk and stored an entry in a sqlite3 database.  
  - A script (I have a working perl5 version and I'm trying to port it to perl6) reads the database file and writes m3u playlist files.  
  - Mpd and it's clients (a music player, my guess is it's all C code) need to be able to open the music files using the paths in the m3u playlists.

My problem is I can't read the URIs from the database and transform them back to the file names on disk using perl6.  I'm probably doing it wrong.  The the data on the disk may not be in perl6's ideal format, but that's the data.  Everything else including perl5 could handle it.

At the moment, my perl6 transformation can be described as 

    $fh.print( $sth.allrows.flat
                           .map( *.subst: /^ 'file://' /, '' )
                           .map( { S :g / '+' /{uri_escape('+')}/ } )
                           .map( { uri_unescape($_) } )
                           .map( *.IO.relative($library_root.IO.abspath) )
                           .map( * ~ "\n" ) );

  - read the URI from the db
  - strip file:// from the front
  - escape '+' (banshee doesn't escape them.  Perl6's uri_unescape() will turn them to ' '.)
  - call uri_unescape() (we get 2 byte 'ù' here)
  - make the path relative to the root of the music library directory
  - add newlines

For reference the code from the perl5  version is

    while(my $row = $sth->fetchrow_arrayref){
        print $fh (URI->new( $row->[0] )->rel($base_uri)->path
                   =~ s/%([0-9A-Fa-f]{2})/chr(hex($1))/egr), "\n";
    }

I'm not calling perl5's uri_unescape(), but all it does is '$str =~ s/%([0-9A-Fa-f]{2})/chr(hex($1))/eg'.  I tried using the regex approach to unescaping in perl6, but hit another problem and was told to use uri_unescape().  (The 3 byte 'ù' became 5 byte 'uÌ').

    $fh.print( $sth.allrows.flat
                           .map( *.subst: /^ 'file://' /, '' )
                           .map({ S:g/'%' ( <xdigit>**2 )/{ :16(~$0).chr }/ })
                           .map( *.IO.relative($library_root.IO.abspath) )
                           .map( * ~ "\n" ) );

I wonder if I should be using some datatype other than Str to store path data since Str seems to enforce rules that the filesystem does not.

======

In filesystem (3 byte 'ù')

    ls /space/pub/music/mp3/Musopen\ DVD/Brahms\ -\ Symphony\ No\ 1\ in\ C\ Major/Symphony\ No.\ 1\ in\ C\ Minor\,\ Op.\ 68\ -\ IV.\ Adagio\ -\ Più\ andante\ -\ Allegro\ non\ troppo\,\ ma\ con\ brio.mp3

    /space/pub/music/mp3/Musopen DVD/Brahms - Symphony No 1 in C Major/Symphony No. 1 in C Minor, Op. 68 - IV. Adagio - Più andante - Allegro non troppo, ma con brio.mp3

======

In sqlite DB created/used by banshee ('ù' is 'u%CC%80')

    select * from CoreTracks where Uri like '%Symphony%20No.%201%20in%20C%20Minor,%20Op.%2068%20-%20IV.%20Adagio%';

    file:///space/pub/music/mp3/Musopen%20DVD/Brahms%20-%20Symphony%20No%201%20in%20C%20Major/Symphony%20No.%201%20in%20C%20Minor,%20Op.%2068%20-%20IV.%20Adagio%20-%20Piu%CC%80%20andante%20-%20Allegro%20non%20troppo,%20ma%20con%20brio.mp3

======

Result after uri_unescape()  (3 byte 'ù' is now 2 byte 'ù')

    perl6 -e 'use URI::Escape; uri_unescape("file:///space/pub/music/mp3/Musopen%20DVD/Brahms%20-%20Symphony%20No%201%20in%20C%20Major/Symphony%20No.%201%20in%20C%20Minor,%20Op.%2068%20-%20IV.%20Adagio%20-%20Piu%CC%80%20andante%20-%20Allegro%20non%20troppo,%20ma%20con%20brio.mp3").say'

    file:///space/pub/music/mp3/Musopen DVD/Brahms - Symphony No 1 in C Major/Symphony No. 1 in C Minor, Op. 68 - IV. Adagio - Più andante - Allegro non troppo, ma con brio.mp3

======

remove 'file://' and ls the perl6 filename

    ls '/space/pub/music/mp3/Musopen DVD/Brahms - Symphony No 1 in C Major/Symphony No. 1 in C Minor, Op. 68 - IV. Adagio - Più andante - Allegro non troppo, ma con brio.mp3'

    ls: cannot access /space/pub/music/mp3/Musopen DVD/Brahms - Symphony No 1 in C Major/Symphony No. 1 in C Minor, Op. 68 - IV. Adagio - Più andante - Allegro non troppo, ma con brio.mp3: No such file or directory

**Comment by samcv** [comment]
@dmhursh 
So what you want to do is read the Banshee database with `'file'.IO.slurp(:enc('utf8-c8'))`.
utf8-c8 will retain any non NFC form Unicode or any corrupt UTF-8 and retain the data. Then if you wrote the string out to a file using 'thing'.IO.spurt($string, :enc('utf8-c8')), it will be exactly the same as it was before.
```perl6
dir[0].Str.encode('utf8-c8').decode('utf8')
# this will encode the file's name into NFC form Unicode in case you wanted to take
# the renaming approach
```
I am still not sure how we can URI encode a utf8-c8 string though.

**Comment by samcv** [comment]
@dmhursh also me and @jnthn were talking on IRC in #moarvm
https://irclog.perlgeek.de/moarvm/2017-02-09#i_14071839

Seems we need to come up with an interface to access the original codepoints of that string.

**Comment by dmhursh** [comment]
@samcv, thanks for looking into it.  If I understand right, it's more a matter of decoding the URI and preserving what it represented.  Think I can use *.encode('utf8').decode('utf8-c8')?  (I'll try that too I suppose just out of curiosity.)

**Comment by samcv** [comment]
Well you are reading a unicode database file right? And that file contains the problem filename? You should open that file with :enc('utf8-c8') and it will retain the same data.

You then need to go from what is in that file to a URI right? or do you go from a URI _to_ the file?

**Comment by dmhursh** [comment]
That's not quite right.  I'm using connect() from DBIish to access the database file.  The database file is a sqlite3 database file.  I believe DBIish is using the sqlite3 C API.

Also I'm not generating the URI.  I'm getting the URI from the the database.  I'm unescaping the URI and trying to get a path I can write in a playlist file.  I suppose the playlist file could be unicode, but the string in the playlist has to match the name on disk or the music player will not be able to open it.

**Comment by dmhursh** [comment]
I've created a recreate script.  When ever I try to upload it I get " Something went really wrong, and we can’t process that file. Try again."  I'll see what I can do...

**Comment by dmhursh** [comment]
[Uploading recreate.zip…]()

It says it's uploading.  We'll see.

It's in a zipfile because github only allows certain types of attachments.  The zip file had 4 files in it.

- recreate.pl6 -- This is the script.  It reads and writes files in the current directory.  Check it to make sure I didn't do something really bad.
- expected.txt -- This is the script I expect to be able to decode from the database.  I didn't remove the 'ftp://'.  I just wanted to keep it simple.
- my-found.txt  -- This is a sample of what I am able to read from the DB.  When you run the script, it will create a file named "found.txt".
- sample.db -- This is a database file with a single table holding a single row.  It's still kinda big.  I took the real DB and just dropped the uninteresting rows and tables.  Looks like sqlite didn't shrink it.

**Comment by dmhursh** [comment]
Upload isn't working for me.  I put it here.  http://filebin.ca/3Bs49AZXK4GX/recreate.zip

**Comment by samcv** [comment]
@dmhursh I got it working, but it's pretty hacky and only works because all of the URI encoded codepoints bit into 1 byte.

Also, the character that is messing things up is 0x80 which is a padding character or something? This seems to be the source of all of our woes!
00000070  2e 20 41 64 61 67 69 6f  20 2d 20 50 69 75 cc **80**  |. Adagio - Piu..|

**Comment by samcv** [comment]
Actually the 0x80 is there even if you don't do utf8-c8, so that's not the issue, spoke too soon. Regardless it does show this filename is odd :P

**Comment by samcv** [comment]
I have made a Pull Request for the URI::Escape module here, which allows you to decode in utf8-c8: https://github.com/perl6-community-modules/uri/pull/32

**Comment by samcv** [comment]
@dmhursh the PR has been merged, so if you update the `URI` module then you will be able to use
```perl6
uri-decode($string, :enc('utf8-c8'))
```
🌟

**Comment by samcv** [comment]
Resolved, closing!

**Comment by dmhursh** [comment]
Hi.  Sorry for the late reply.  I recently started playing with rakudo-star-2017.04.  I ran my sample scripts and got the following.  I don't intend to reopen this because it's not really pressing for me at the moment and it's not fair to string this out for you.  I figure I'll file the experiment under "unicode-is-hard" or "file names don't unicode".

The perl5 version produces:
```
00000060: 202d 2050 6975 cc80 2061 6e64 616e 7465   - Piu.. andante
00000070: 202d 2041 6c6c 6567 726f 206e 6f6e 2074   - Allegro non t
00000080: 726f 7070 6f2c 206d 6120 636f 6e20 6272  roppo, ma con br
00000090: 696f 2e6d 7033 0a                        io.mp3.
```

The perl6 version running rakudo-star-2017.01 produces:
```
00000060: 202d 2050 69c3 b920 616e 6461 6e74 6520   - Pi.. andante 
00000070: 2d20 416c 6c65 6772 6f20 6e6f 6e20 7472  - Allegro non tr
00000080: 6f70 706f 2c20 6d61 2063 6f6e 2062 7269  oppo, ma con bri
00000090: 6f2e 6d70 330a                           o.mp3.
```

The perl6 version running rakudo-star-2017.04 produces:
```
00000060: 202d 2050 6975 f48f bfbd 7843 43f4 8fbf   - Piu....xCC...
00000070: bd78 3830 2061 6e64 616e 7465 202d 2041  .x80 andante - A
00000080: 6c6c 6567 726f 206e 6f6e 2074 726f 7070  llegro non tropp
00000090: 6f2c 206d 6120 636f 6e20 6272 696f 2e6d  o, ma con brio.m
000000a0: 7033 0a                                  p3.
```

As a part of porting from rakudo-star-2017.01 to rakudo-star-2017.04 I made the following changes:
```
98,100c97,99
<                            .map( { S :g / '+' /{uri-escape('+')}/ } )
<                            .map( { uri-unescape($_, :enc('utf8-c8')) } )
<                            .map( *.IO.relative($library_root.IO.absolute) )
---
>                            .map( { S :g / '+' /{uri_escape('+')}/ } )
>                            .map( { uri_unescape($_) } )
>                            .map( *.IO.relative($library_root.IO.abspath) )
```

**Comment by dmhursh** [comment]
Just for completeness rakudo-star-2017.07 produces

```
00000060: 202d 2050 6975 f48f bfbd 7843 43f4 8fbf   - Piu....xCC...
00000070: bd78 3830 2061 6e64 616e 7465 202d 2041  .x80 andante - A
00000080: 6c6c 6567 726f 206e 6f6e 2074 726f 7070  llegro non tropp
00000090: 6f2c 206d 6120 636f 6e20 6272 0d6f 2e6d  o, ma con br.o.m
000000a0: 7033 0a                                  p3.
```
On a quick skim, I guess that's the same as rakudo-star-2017.04
