### ISSUE TITLE
creating lots of really big numbers uses a ton of ram

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#545]
E.g., `my ($x,$y,$i) = (0,1,1); while ($i < 200000) {$y += $x ; $x = $y - $x ; $i += 1 } ; say $y;` allocates 3.6G. Some discussion with @timo here:
https://irclog.perlgeek.de/moarvm/2017-03-05#i_14206954

**Comment by timo** [comment]
executive summary: a bigint takes only very little space in the nursery, but it can hold on to a gigantic buffer.

we probably want a solution similar to the "bytes promoted since last major collection" but instead of turning a minor into a major collection, we'd do a minor collection before the nursery has hit its limit.

of course, if we come up with something smarter, that'd be fantastic as well!

**Comment by jnthn** [comment]
The cheapest way would just be to subtract some from the nursery alloc limit - that is, shorten the nursery on large allocations.

**Comment by MasterDuke17** [comment]
You mean in src/core/alloc.h?

**Comment by MasterDuke17** [comment]
For future reference, "I think when we produce a new bigint [in src/math/bigintops.c] (that's actually big), before we hand it back to the user, we [should] take the number of digits and [carefully] use that to influence the nursery size" - jnthn

**Comment by MasterDuke17** [comment]
Fixed in 63430ac
