### ISSUE TITLE
4ce52ef causes NQP to segfault at build on alpine/musl

### ISSUE THREAD

**Issue by JRaspass** [MoarVM/MoarVM#666]
2017.07 Rakudo/NQP/Moar build fine on alpine linux, 2017.08 does not.

Bisecting reveals that the NQP/Moar pair f6c2458/75f9ac3 work fine, but bumping Moar up by one commit to 4ce52ef48fc918a1cb08a89cdaf7b4ab8caab135 causes a segfault when NQP tries to run Moar. The same error is seen when using the latest master for both.

The error is:
```
/usr/bin/moar --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --module-path=gen/moar/stage1 --setting-path=gen/moar/stage1 \
    --setting=NQPCORE --no-regex-lib --target=mbc \
    --output=gen/moar/stage1/NQPHLL.moarvm gen/moar/stage1/NQPHLL.nqp
Segmentation fault (core dumped)
make: *** [Makefile:272: gen/moar/stage1/NQPHLL.moarvm] Error 139
```

A simple Dockerfile to reproduce the error:
```
FROM alpine:edge

RUN apk add --no-cache gcc git linux-headers make musl-dev perl

# BAD  4ce52ef
# GOOD 75f9ac3

# MoarVM
RUN git clone git://github.com/MoarVM/MoarVM \
 && cd MoarVM                                \
 && git checkout 4ce52ef                     \
 && ./Configure.pl --prefix=/usr             \
 && make -j`nproc` install

# NQP
RUN git clone git://github.com/perl6/nqp \
 && cd nqp                               \
 && git checkout f6c2458                 \
 && ./Configure.pl --prefix=/usr         \
 && make -j`nproc` install
```

**Comment by JRaspass** [comment]
Well it's definitely 4ce52ef48fc918a1cb08a89cdaf7b4ab8caab135 that breaks things because simply reverting that commit causes master of both to build cleanly, like so:

```
FROM alpine:edge

RUN apk add --no-cache gcc git linux-headers make musl-dev perl

RUN git config --global user.email 'foo@bar.com' \
 && git config --global user.name  'foo bar'

# MoarVM
RUN git clone git://github.com/MoarVM/MoarVM \
 && cd MoarVM                                \
 && git revert 4ce52ef                       \
 && ./Configure.pl --prefix=/usr             \
 && make -j`nproc` install

# NQP
RUN git clone git://github.com/perl6/nqp \
 && cd nqp                               \
 && ./Configure.pl --prefix=/usr         \
 && make -j`nproc` install
```

But past that I'm not really sure what the fix is, my hunch is that more ops than before are getting marked with the MVM_CFG_BB_END flag and this is then trigger something else. I presume since travis and such is passing this doesn't affect glibc, which is a little odd. :-S

I'm also failing to get docker to give me a nice coredump ATM, I think you need to run a privileged container, and probably mount /proc in or do something with ulimit, *shrugs*. Either way I'm pretty out of my element here, and would appreciate someone with a bit more C/MoarVM knowledge than I to debug what's going on, @jnthn perhaps?

I'm not sure where this lies on the priority scale, but I presume we'd like a Rakudo Alpine Docker container at some point so we can hang with the other cool kids^Wlanguages ;-) And this bug blocks that :-(

**Comment by jnthn** [comment]
I suspect the issue may be a stack overflow due to too small a stack being provided.

The optimizer has a number of places where it works recursively over the dominance tree or does a DFS over the CFG. The maximum recursion depth is related to the depth of that tree or the deepest CFG path, and the commit in question splits basic blocks more finely (later commits depend on it for correctness) and thus may deepen the tree/graph.

There is a hard limit on the code size we will optimize (this is sensible in general, not just for controlling this issue), which puts an upper limit on the number of basic blocks and thus on the stack space needed. However, it seems [the Alpine default stack size is smaller than usual, as others have discovered](https://github.com/lovell/sharp/issues/242). A patch to give threads a more typical stack size would be the easiest way forward. An alternative - but it requires more work and understanding of the code in question - would be to rewrite things using a recursive algorithm to instead use an iterative one.

**Comment by JRaspass** [comment]
This is now fixed as of https://github.com/MoarVM/MoarVM/commit/5528083df795e41ec05eb5b47288c9bec35e9def thanks @samcv
