### ISSUE TITLE
GCC warning during the compilaton

### ISSUE THREAD

**Issue by AlexDaniel** [MoarVM/MoarVM#783]
```
gcc -DHAVE_CONFIG_H   -I../src -I../src  -fPIC -Wall -Wextra -Werror=declaration-after-statement -Werror=pointer-arith -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_TRACING=0 -DMVM_CGOTO=1 -DMVM_RDTSCP=1 -MT atomic_ops.o -MD -MP -MF .deps/atomic_ops.Tpo -c -o atomic_ops.o atomic_ops.c
In file included from atomic_ops.c:73:0:
atomic_ops/sysdeps/standard_ao_double_t.h:36:37: warning: ‘-pedantic’ is not an option that controls warnings [-Wpragmas]
 #     pragma GCC diagnostic ignored "-pedantic"
                                     ^~~~~~~~~~~
```

**Comment by lizmat** [comment]
isn’t that --pedantic ?

**Comment by zoffixznet** [comment]
Was fixed upstream in last August: https://github.com/ivmai/libatomic_ops/issues/27

**Comment by samcv** [comment]
This is probably fixed since https://github.com/MoarVM/MoarVM/commit/a342936cdecafbbd817c886014d6d224785ea318
We are now up to 7.6.2 of libatomic released Dec of 2017. Now we have libatomic in its own repository and and with some tricks to get our modified tree merged into the actual libatomic ops, should be much easier to update from now on.
